In [1]:
from pathlib import Path

script = '''import pandas as pd

INPUT_FILE = "/home/sina/bigdata-lab/storage_lab/metadata/metadata_clean.csv"
OUTPUT_FILE = "/home/sina/bigdata-lab/storage_lab/metadata/metadata_clean.parquet"


def convert_to_parquet():
    df = pd.read_csv(INPUT_FILE)

    df.to_parquet(
        OUTPUT_FILE,
        engine="pyarrow",
        index=False
    )

    print(f"Parquet created: {OUTPUT_FILE}")
    print(f"Rows: {len(df):,}")
    print(f"Columns: {len(df.columns)}")


if __name__ == "__main__":
    convert_to_parquet()
'''

path = Path("/home/sina/bigdata-lab/storage_lab/scripts/convert_metadata_to_parquet.py")
path.write_text(script)

print(f"Created: {path}")

Created: /home/sina/bigdata-lab/storage_lab/scripts/convert_metadata_to_parquet.py

## File Check

In [2]:
import pandas as pd

df = pd.read_csv(
    "/home/sina/bigdata-lab/storage_lab/metadata/metadata_clean.csv",
    low_memory=False,
    parse_dates=["ModificationTimestamp"]
)

In [9]:
import pandas as pd

df = pd.read_parquet(
    "/home/sina/bigdata-lab/storage_lab/metadata/metadata_clean.parquet"
)

In [3]:
import pandas as pd

file = "/home/sina/bigdata-lab/storage_lab/metadata/metadata_clean.parquet"

df = pd.read_parquet(file)

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nFirst 2 rows:")
display(df.head(2))

Shape: (4942657, 25)

Columns:
['Source', 'Zone', 'TableName', 'LogicalTableName', 'FileName', 'FileFormat', 'TotalSizeBytes', 'FileCount', 'IsPartitioned', 'PartitionColumn', 'PartitionName', 'PartitionPattern', 'HasHourlyPartition', 'HourlyPartitionName', 'ModificationTimestamp', 'ModificationDate', 'ModificationTime', 'Year', 'Month', 'Day', 'YearMonth', 'Hour', 'ParentPath', 'FullPath', 'Type']

Data types:
Source                     str
Zone                       str
TableName                  str
LogicalTableName           str
FileName                   str
FileFormat                 str
TotalSizeBytes           int64
FileCount                int64
IsPartitioned             bool
PartitionColumn            str
PartitionName              str
PartitionPattern           str
HasHourlyPartition        bool
HourlyPartitionName        str
ModificationTimestamp      str
ModificationDate           str
ModificationTime           str
Year                     int64
Month                    int64
Day                      int64
YearMonth                  str
Hour                     int64
ParentPath                 str
FullPath                   str
Type                       str
dtype: object

First 2 rows:

,Source,Zone,TableName,LogicalTableName,FileName,FileFormat,TotalSizeBytes,FileCount,IsPartitioned,PartitionColumn,...,ModificationDate,ModificationTime,Year,Month,Day,YearMonth,Hour,ParentPath,FullPath,Type
0,source_04,BRONZE,sales_detail,sales_detail,sales_detail_00005.dat,dat,135266304,1,False,NaN,...,2026-09-29,15:21:45,2026,9,29,2026-09,15,/home/sina/bigdata-lab/storage_lab/bronze/sour...,/home/sina/bigdata-lab/storage_lab/bronze/sour...,dat
1,source_04,BRONZE,sales_detail,sales_detail,sales_detail_00004.dat,dat,128974848,1,False,NaN,...,2026-09-29,15:49:15,2026,9,29,2026-09,15,/home/sina/bigdata-lab/storage_lab/bronze/sour...,/home/sina/bigdata-lab/storage_lab/bronze/sour...,dat

# 1. Metadata Schema & Data Quality Validation

This section validates the analytical metadata dataset before performing storage analysis.

The validation process covers the following areas:

### 1.1 Basic Dataset Validation

### 1.2 Missing Value Validation

### 1.3 Duplicate Record Validation

### 1.4 Data Type Validation

### 1.5 File Metadata Validation

### 1.6 Partition Metadata Validation

### 1.7 Date & Time Validation

### 1.8 Path & Structure Validation

### 1.9 Logical Consistency Validation

### 1.10 Validation Summary

---

## Validation Result

The validated Parquet dataset will be used as the trusted input for the subsequent storage analysis.

### 1.1 Basic Dataset Validation
- Row count
- Column count
- Column names
- Dataset structure
- Dupplicate Check
- Sample records

In [4]:
import pandas as pd

FILE = "/home/sina/bigdata-lab/storage_lab/metadata/metadata_clean.parquet"

df = pd.read_parquet(FILE)

print("=" * 70)
print("METADATA PARQUET VALIDATION")
print("=" * 70)

print(f"\nRows    : {len(df):,}")
print(f"Columns : {len(df.columns)}")

print("\n--- Schema ---")
print(df.dtypes)

print("\n--- Missing Values ---")
print(df.isna().sum())

print("\n--- Duplicate Rows ---")
print(f"Duplicates: {df.duplicated().sum():,}")

print("\n--- FileCount ---")
print(df["FileCount"].value_counts(dropna=False))

print("\n--- FileFormat ---")
print(df["FileFormat"].value_counts(dropna=False))

print("\n--- Zone ---")
print(df["Zone"].value_counts(dropna=False))

print("\n--- Partition Status ---")
print(df["IsPartitioned"].value_counts(dropna=False))

print("\n--- Sample ---")
display(df.head(5))

======================================================================
METADATA PARQUET VALIDATION
======================================================================

Rows    : 4,942,657
Columns : 25

--- Schema ---
Source                     str
Zone                       str
TableName                  str
LogicalTableName           str
FileName                   str
FileFormat                 str
TotalSizeBytes           int64
FileCount                int64
IsPartitioned             bool
PartitionColumn            str
PartitionName              str
PartitionPattern           str
HasHourlyPartition        bool
HourlyPartitionName        str
ModificationTimestamp      str
ModificationDate           str
ModificationTime           str
Year                     int64
Month                    int64
Day                      int64
YearMonth                  str
Hour                     int64
ParentPath                 str
FullPath                   str
Type                       str
dtype: object

--- Missing Values ---
Source                       0
Zone                         0
TableName                    0
LogicalTableName             0
FileName                     0
FileFormat                   0
TotalSizeBytes               0
FileCount                    0
IsPartitioned                0
PartitionColumn            378
PartitionName              378
PartitionPattern           378
HasHourlyPartition           0
HourlyPartitionName      41955
ModificationTimestamp        0
ModificationDate             0
ModificationTime             0
Year                         0
Month                        0
Day                          0
YearMonth                    0
Hour                         0
ParentPath                   0
FullPath                     0
Type                         0
dtype: int64

--- Duplicate Rows ---
Duplicates: 0

--- FileCount ---
FileCount
1    4942657
Name: count, dtype: int64

--- FileFormat ---
FileFormat
json       3400502
dat         757090
csv         401494
txt         373631
parquet       9940
Name: count, dtype: int64

--- Zone ---
Zone
BRONZE    4942657
Name: count, dtype: int64

--- Partition Status ---
IsPartitioned
True     4942279
False        378
Name: count, dtype: int64

--- Sample ---

,Source,Zone,TableName,LogicalTableName,FileName,FileFormat,TotalSizeBytes,FileCount,IsPartitioned,PartitionColumn,...,ModificationDate,ModificationTime,Year,Month,Day,YearMonth,Hour,ParentPath,FullPath,Type
0,source_04,BRONZE,sales_detail,sales_detail,sales_detail_00005.dat,dat,135266304,1,False,NaN,...,2026-09-29,15:21:45,2026,9,29,2026-09,15,/home/sina/bigdata-lab/storage_lab/bronze/sour...,/home/sina/bigdata-lab/storage_lab/bronze/sour...,dat
1,source_04,BRONZE,sales_detail,sales_detail,sales_detail_00004.dat,dat,128974848,1,False,NaN,...,2026-09-29,15:49:15,2026,9,29,2026-09,15,/home/sina/bigdata-lab/storage_lab/bronze/sour...,/home/sina/bigdata-lab/storage_lab/bronze/sour...,dat
2,source_04,BRONZE,sales_detail,sales_detail,sales_detail_00007.dat,dat,117440512,1,False,NaN,...,2026-09-29,15:43:32,2026,9,29,2026-09,15,/home/sina/bigdata-lab/storage_lab/bronze/sour...,/home/sina/bigdata-lab/storage_lab/bronze/sour...,dat
3,source_04,BRONZE,sales_detail,sales_detail,sales_detail_00002.dat,dat,114294784,1,False,NaN,...,2026-09-30,15:02:31,2026,9,30,2026-09,15,/home/sina/bigdata-lab/storage_lab/bronze/sour...,/home/sina/bigdata-lab/storage_lab/bronze/sour...,dat
4,source_04,BRONZE,sales_detail,sales_detail,sales_detail_00009.dat,dat,115343360,1,False,NaN,...,2026-06-22,15:43:37,2026,6,22,2026-06,15,/home/sina/bigdata-lab/storage_lab/bronze/sour...,/home/sina/bigdata-lab/storage_lab/bronze/sour...,dat

### 1.2 Missing Value Validation
- Missing values by column
- Missing-value percentage
- Identification of expected vs unexpected missing values

In [5]:
# Expected vs Unexpected Missing Values

expected_missing = {
    "HourlyPartitionName": df["HasHourlyPartition"].eq(False),
    "PartitionColumn": ~df["IsPartitioned"],
    "PartitionName": ~df["IsPartitioned"],
    "PartitionPattern": ~df["IsPartitioned"]
}

print("=" * 70)
print("EXPECTED vs UNEXPECTED MISSING VALUES")
print("=" * 70)

for column, expected_condition in expected_missing.items():

    missing_mask = df[column].isna()

    expected = (missing_mask & expected_condition).sum()
    unexpected = (missing_mask & ~expected_condition).sum()

    print(f"\n{column}")
    print(f"  Expected Missing   : {expected:,}")
    print(f"  Unexpected Missing : {unexpected:,}")

======================================================================
EXPECTED vs UNEXPECTED MISSING VALUES
======================================================================

HourlyPartitionName
  Expected Missing   : 41,955
  Unexpected Missing : 0

PartitionColumn
  Expected Missing   : 378
  Unexpected Missing : 0

PartitionName
  Expected Missing   : 378
  Unexpected Missing : 0

PartitionPattern
  Expected Missing   : 378
  Unexpected Missing : 0

### 1.3 Duplicate Record Validation
- Full-row duplicates
- Duplicate file paths
- Duplicate metadata records

In [6]:
print("=" * 70)
print("DUPLICATE RECORD VALIDATION")
print("=" * 70)

full_duplicates = df.duplicated().sum()

print(f"\nFull-row duplicates: {full_duplicates:,}")

======================================================================
DUPLICATE RECORD VALIDATION
======================================================================

Full-row duplicates: 0

### 1.4 Data Type Validation
- Numeric columns
- Boolean columns
- Date and timestamp columns
- String columns
- Unexpected data types

In [11]:
# Normalize ModificationTimestamp
df["ModificationTimestamp"] = pd.to_datetime(
    df["ModificationTimestamp"],
    errors="coerce"
)

In [12]:
expected_types = {
    "TotalSizeBytes": "numeric",
    "FileCount": "numeric",
    "Year": "numeric",
    "Month": "numeric",
    "Day": "numeric",
    "Hour": "numeric",
    "IsPartitioned": "boolean",
    "HasHourlyPartition": "boolean",
    "ModificationTimestamp": "datetime"
}

print("DATA TYPE VALIDATION")
print("=" * 70)

for column, expected in expected_types.items():
    if expected == "numeric":
        valid = pd.api.types.is_numeric_dtype(df[column])
    elif expected == "boolean":
        valid = pd.api.types.is_bool_dtype(df[column])
    elif expected == "datetime":
        valid = pd.api.types.is_datetime64_any_dtype(df[column])
    else:
        valid = False

    print(f"{column:25} : {'PASS' if valid else 'FAIL'}")

DATA TYPE VALIDATION
======================================================================
TotalSizeBytes            : PASS
FileCount                 : PASS
Year                      : PASS
Month                     : PASS
Day                       : PASS
Hour                      : PASS
IsPartitioned             : PASS
HasHourlyPartition        : PASS
ModificationTimestamp     : PASS

### 1.5 File Metadata Validation
- File size validity
- File count validity
- File format consistency
- File name consistency
- Empty-directory records

In [13]:
print("FILE METADATA VALIDATION")
print("=" * 70)

print(f"Negative FileSize      : {(df['TotalSizeBytes'] < 0).sum():,}")
print(f"Negative FileCount     : {(df['FileCount'] < 0).sum():,}")
print(f"Zero-size files        : {((df['TotalSizeBytes'] == 0) & (df['FileCount'] > 0)).sum():,}")
print(f"Invalid FileCount      : {(~df['FileCount'].isin([0, 1])).sum():,}")
print(f"Missing FileFormat     : {df['FileFormat'].isna().sum():,}")

file_rows = df["FullPath"].notna() & (df["FullPath"] != "")

print(f"File rows              : {file_rows.sum():,}")
print(f"FileName missing       : {df.loc[file_rows, 'FileName'].isna().sum():,}")

FILE METADATA VALIDATION
======================================================================
Negative FileSize      : 0
Negative FileCount     : 0
Zero-size files        : 0
Invalid FileCount      : 0
Missing FileFormat     : 0
File rows              : 4,942,657
FileName missing       : 0

### 1.6 Partition Metadata Validation
- Partition flag consistency
- Partition column consistency
- Partition name consistency
- Partition pattern consistency
- Hourly partition consistency

In [14]:
print("PARTITION METADATA VALIDATION")
print("=" * 70)

partitioned = df["IsPartitioned"] == True
non_partitioned = ~partitioned

print(f"Partitioned records                : {partitioned.sum():,}")
print(f"Non-partitioned records            : {non_partitioned.sum():,}")

print(f"PartitionColumn missing             : {df.loc[partitioned, 'PartitionColumn'].isna().sum():,}")
print(f"PartitionName missing               : {df.loc[partitioned, 'PartitionName'].isna().sum():,}")
print(f"PartitionPattern missing            : {df.loc[partitioned, 'PartitionPattern'].isna().sum():,}")

print(f"Unexpected PartitionColumn          : {df.loc[non_partitioned, 'PartitionColumn'].notna().sum():,}")
print(f"Unexpected PartitionName            : {df.loc[non_partitioned, 'PartitionName'].notna().sum():,}")
print(f"Unexpected PartitionPattern         : {df.loc[non_partitioned, 'PartitionPattern'].notna().sum():,}")

hourly = df["HasHourlyPartition"] == True

print(f"\nHourly-partitioned records          : {hourly.sum():,}")
print(f"HourlyPartitionName missing         : {df.loc[hourly, 'HourlyPartitionName'].isna().sum():,}")

PARTITION METADATA VALIDATION
======================================================================
Partitioned records                : 4,942,279
Non-partitioned records            : 378
PartitionColumn missing             : 0
PartitionName missing               : 0
PartitionPattern missing            : 0
Unexpected PartitionColumn          : 0
Unexpected PartitionName            : 0
Unexpected PartitionPattern         : 0

Hourly-partitioned records          : 4,900,702
HourlyPartitionName missing         : 0

### 1.7 Date & Time Validation
- Year / Month / Day consistency
- YearMonth consistency
- Hour consistency
- Modification date consistency
- Partition date consistency

In [15]:
print("DATE & TIME VALIDATION")
print("=" * 70)

# Validate only populated date/time fields to avoid treating expected NaN values as invalid.
month_valid = df["Month"].isna() | df["Month"].between(1, 12)
day_valid = df["Day"].isna() | df["Day"].between(1, 31)
hour_valid = df["Hour"].isna() | df["Hour"].between(0, 23)

print(f"Invalid Month   : {(~month_valid).sum():,}")
print(f"Invalid Day     : {(~day_valid).sum():,}")
print(f"Invalid Hour    : {(~hour_valid).sum():,}")

# Build the expected YearMonth only where Year and Month are available.
year_month_check = pd.Series(pd.NA, index=df.index, dtype="string")
date_parts = df["Year"].notna() & df["Month"].notna()
year_month_check.loc[date_parts] = (
    df.loc[date_parts, "Year"].astype("Int64").astype("string")
    + "-"
    + df.loc[date_parts, "Month"].astype("Int64").astype("string").str.zfill(2)
)

yearmonth_valid = (
    df["YearMonth"].isna()
    | year_month_check.isna()
    | (df["YearMonth"].astype("string") == year_month_check)
)

print(f"Invalid YearMonth : {(~yearmonth_valid).sum():,}")

DATE & TIME VALIDATION
======================================================================
Invalid Month   : 0
Invalid Day     : 0
Invalid Hour    : 0
Invalid YearMonth : 0

### 1.8 Path & Structure Validation
- Source consistency
- Zone consistency
- Table name consistency
- ParentPath consistency
- FullPath consistency
- FileName consistency

In [16]:
print("PATH & STRUCTURE VALIDATION")
print("=" * 70)

# Vectorized path validation. Avoid df.apply(axis=1), which is very slow
# and can make the kernel appear to hang on large metadata datasets.
full_path = df["FullPath"].astype("string")

# Source is expected to be the directory immediately before the table directory.
expected_source = full_path.str.extract(r"/Trusted_Data/([^/]+)/(?:TZ|RZ)_", expand=False)
source_check = (
    df["Source"].isna()
    | full_path.isna()
    | expected_source.isna()
    | (df["Source"].astype("string") == expected_source)
)

# Extract the table directory from the path and compare it with TableName.
expected_table = full_path.str.extract(r"/((?:TZ|RZ)_[^/]+)(?:/|$)", expand=False)
table_check = (
    df["TableName"].isna()
    | full_path.isna()
    | expected_table.isna()
    | (df["TableName"].astype("string") == expected_table)
)

# Compare FileName with the final path component.
path_filename = full_path.str.rsplit("/", n=1).str[-1]
filename_check = (
    df["FileName"].isna()
    | full_path.isna()
    | (df["FileName"].astype("string") == path_filename)
)

print(f"Invalid Source in path     : {(~source_check).sum():,}")
print(f"Invalid TableName in path  : {(~table_check).sum():,}")
print(f"Invalid FileName in path   : {(~filename_check).sum():,}")

PATH & STRUCTURE VALIDATION
======================================================================
Invalid Source in path     : 0
Invalid TableName in path  : 0
Invalid FileName in path   : 0

### 1.9 Logical Consistency Validation
- Cross-column consistency checks
- FileCount vs file-level records
- FileSize vs FileCount relationships
- Partition-related logical rules
- Identification of contradictory records

In [17]:
print("LOGICAL CONSISTENCY VALIDATION")
print("=" * 70)

# Section 1.9 combines the results of the previous validations
# and checks relationships between related metadata columns.
checks = {
    "File rows have FileCount=1":
        (file_rows & (df["FileCount"] != 1)).sum(),

    "Empty directories have FileCount=0":
        ((df["Type"] == "EMPTY_DIRECTORY") & (df["FileCount"] != 0)).sum(),

    "Empty directories have no FileName":
        ((df["Type"] == "EMPTY_DIRECTORY") & df["FileName"].notna()).sum(),

    "Non-partitioned rows have no partition metadata":
        ((~partitioned) & (
            df["PartitionColumn"].notna()
            | df["PartitionName"].notna()
            | df["PartitionPattern"].notna()
        )).sum(),

    "Non-hourly rows have no hourly partition metadata":
        ((~hourly) & df["HourlyPartitionName"].notna()).sum(),

    "File rows have FileName":
        (file_rows & df["FileName"].isna()).sum(),

    "File rows have positive size":
        (file_rows & (df["TotalSizeBytes"] <= 0)).sum(),
}

for check, failures in checks.items():
    print(f"{check:55} : {failures:,}")

LOGICAL CONSISTENCY VALIDATION
======================================================================
File rows have FileCount=1                              : 0
Empty directories have FileCount=0                      : 0
Empty directories have no FileName                      : 0
Non-partitioned rows have no partition metadata         : 0
Non-hourly rows have no hourly partition metadata       : 0
File rows have FileName                                 : 0
File rows have positive size                            : 0

### 1.10 Validation Summary
- Total validation checks
- Passed checks
- Failed checks
- Warnings
- Data quality issues requiring attention

In [18]:
print("=" * 70)
print("VALIDATION SUMMARY")
print("=" * 70)

duplicate_fullpath = df["FullPath"].duplicated().sum()

# Keep each validation result as a separate metric so that the same
# record is not incorrectly interpreted as multiple unique records.
summary = {
    "Full-row duplicates": full_duplicates,
    "Duplicate FullPath": duplicate_fullpath,
    "Negative file sizes": (df["TotalSizeBytes"] < 0).sum(),
    "Negative file counts": (df["FileCount"] < 0).sum(),
    "Invalid months": (~month_valid).sum(),
    "Invalid days": (~day_valid).sum(),
    "Invalid hours": (~hour_valid).sum(),
    "Invalid YearMonth": (~yearmonth_valid).sum(),
    "Invalid Source in path": (~source_check).sum(),
    "Invalid TableName in path": (~table_check).sum(),
    "Invalid FileName in path": (~filename_check).sum(),
    **checks,
}

summary_df = pd.DataFrame.from_dict(
    summary,
    orient="index",
    columns=["IssueCount"]
)

display(summary_df)

failed_checks = (summary_df["IssueCount"] > 0).sum()
total_issue_count = summary_df["IssueCount"].sum()

print(f"\nValidation categories with issues : {failed_checks:,}")
print(f"Reported issue occurrences        : {total_issue_count:,}")
print("Note: issue occurrences are not necessarily unique records because one record may fail multiple checks.")

======================================================================
VALIDATION SUMMARY
======================================================================

                                                   IssueCount
Full-row duplicates                                         0
Duplicate FullPath                                          0
Negative file sizes                                         0
Negative file counts                                        0
Invalid months                                              0
Invalid days                                                0
Invalid hours                                               0
Invalid YearMonth                                           0
Invalid Source in path                                      0
Invalid TableName in path                                   0
Invalid FileName in path                                    0
File rows have FileCount=1                                  0
Empty directories have FileCount=0                          0
Empty directories have no FileName                          0
Non-partitioned rows have no partition metadata             0
Non-hourly rows have no hourly partition metadata           0
File rows have FileName                                     0
File rows have positive size                                0

Validation categories with issues : 0
Reported issue occurrences        : 0
Note: issue occurrences are not necessarily unique records because one record may fail multiple checks.

## Validation Result

The validated Parquet dataset will be used as the trusted input for the subsequent storage analysis.

In [19]:
print("=" * 70)
print("FINAL VALIDATION RESULT")
print("=" * 70)

if failed_checks == 0:
    print("PASS - No validation issues detected.")
else:
    print(f"REVIEW REQUIRED - {failed_checks:,} validation categories contain issues.")
    print(f"Reported issue occurrences: {total_issue_count:,}")

======================================================================
FINAL VALIDATION RESULT
======================================================================
PASS - No validation issues detected.